name: Perlcritic check

on:
  pull_request:
  push:
    branches:
    paths:
      - 'FHEM/**'
      - 'lib/**'
      - 't/**'
      - '.github/workflows/perlCritic.yml'

jobs:
  critic:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - uses: reviewdog/action-setup@v1
      with:
        reviewdog_version: latest # Optional. [latest,nightly,v.X.Y.Z]
    - uses: gugod/action-perlcritic@v1
